Tab changes after mentor review
inbarvenko/bookstorefront pull request #1
Opened 2023-08-29 13:00 UTC by inbarvenko

1. включить eslint и устранить его ошибки по всему проекту
2. контент App.tsx вынести в src/core/Core.tsx
3. types – вынести в папку src/types и разнести по файлам, например: src/types/user.ts, src/types/book.ts
4. компоненты вынести в src/components
5. внедрить абсолютные импорты, которые начинаются с src/
6. импорты вида ui/BookCard/BookCard привести к ui/BookCard
7. все .module.tsx переименовать в .styles.ts
8. редакс слайсы вынести в redux/slices
9. убрать санки (createAsyncThunk), получение данных вынести из логики редакса на уровень компонента или хука
10. сделать так, чтобы функции-запросы (в файлах api) возвращали данные или генеhировали ошибку, чтобы можно было отловить ее через try/catch на уровне выше
11. bookApi.tsx – изменить формат файла
12. initSupabase.ts – переименовать в supabase.ts
13. в стэках навигации устранить дубликаты header
14. вместо пропсов navigation и route использовать хуки useNavigation и useRoute
15. пустые функции удалить или оставить в них комментарий с TODO

2023-08-30 15:41 UTC, denis-konakov requested changes

2023-08-30 15:41 UTC, denis-konakov commented on src/components/BookCard/BookCard.tsx
> +                  ? require('src/assets/img/button_save_active.png')
все импорты картинок вынеси в `constants/images.ts` чтобы в компонентах они подключались вот так:
```
import images from 'src/constants/images';
...
source={images.buttonSaveActive}
```

2023-08-30 15:41 UTC, denis-konakov commented on src/components/Button/Button.styles.ts
>  const styles = (props: Props) =>
более корректный нейминг – `getStyles`, потому что это не стили, а функция для их получения

2023-08-30 15:41 UTC, denis-konakov commented on src/components/Button/Button.tsx
> +        styles({width, height, backColor}).appButtonContainer,
функцию для получения стилей нужно вызвать один раз в теле компонента

2023-08-30 15:41 UTC, denis-konakov commented on src/components/Headers/HeaderAuthUser.tsx
> +  _props: BottomTabHeaderProps,
здесь нижнее подчеркивание не нужно

2023-08-30 15:41 UTC, denis-konakov commented on src/components/Input/Input.tsx
> +  info?: boolean;
неочевидный нейминг булеан-переменной

- во-первых, нейминг булеанов лучше всего начинать с `is`, `with`
- во-вторых, по имени любой переменной должно быть понятно, за что она отвечает

в этом случае, насколько я понимаю, `info` отвечает за отображение лейбла-описания в поле ввода, так что примеры хорошего нейминга: `withLabel`, `withDescription`, `withDescriptionLabel`

2023-08-30 15:41 UTC, denis-konakov commented on src/components/Input/Input.tsx
> +          {((inputState.inputFocus && upPlaceholder) || info) && (
такие большие условия лучше выносить в отдельные булеан-переменные в теле функции

2023-08-30 15:41 UTC, denis-konakov commented on src/components/TabBar/TabBar.tsx
> +      <TouchableOpacity
все иконки нужно отрисовать через `state.routes.map`

2023-08-30 15:41 UTC, denis-konakov commented on src/screens/Book/Book.tsx
> +      res.then(data => {
`then` везде меняем на `await`

2023-08-30 15:41 UTC, denis-konakov commented on src/screens/Book/Book.tsx
> +          return;
конструкции с ифом и пустым ретерном лучше в одну строку писать, чтобы чище получилось

2023-08-30 15:41 UTC, denis-konakov commented on src/screens/Favorites/Favorites.tsx
> +type RootStackParamList = {
`ParamList` каждой навигации нужно объявлять непосредственно в файле этой навигации, со списком всех экранов и импортировать на те скрины, где это необходимо

2023-08-30 15:41 UTC, denis-konakov commented on src/screens/Profile/Profile.tsx
> +  // console.log(editState);
комменты нужно удалять перед пушем

2023-08-30 15:41 UTC, denis-konakov commented on src/screens/Profile/Profile.tsx
> +              //На блюр сохраняет значение инпута
к таким комментам нужно добавлять `TODO` и писать, что нужно сделать

2023-08-30 15:43 UTC, denis-konakov commented
дополнительно, нужно сделать так, чтобы при открытии экрана вне таб навигации (например, экрана книги), этот экран перекрывал таб бар

2023-08-31 12:18 UTC, inbarvenko commented on src/components/Headers/HeaderAuthUser.tsx
> +  _props: BottomTabHeaderProps,
'props' is defined but never used. Allowed unused args must match /^_/u (eslint)

2023-08-31 12:18 UTC, inbarvenko commented on src/components/Input/Input.tsx
> +  info?: boolean;
isEditable, withLabel

2023-08-31 12:20 UTC, inbarvenko commented on src/screens/Book/Book.tsx
> +          return;
eslint начинает ругаться - Replace `·return;` with `⏎········return;⏎·····`

2023-08-31 21:36 UTC, denis-konakov commented on src/components/Headers/HeaderAuthUser.tsx
> +  _props: BottomTabHeaderProps,
если пропсы не используются, то объявлять их не нужно

2023-08-31 21:39 UTC, denis-konakov commented on src/screens/Book/Book.tsx
> +          return;
при необходимости, правила линтера можно корректировать в конфигурационном файле
но этот код уже неактуален, так что правки вносить не нужно

2023-09-04 14:38 UTC, denis-konakov requested changes

2023-09-04 14:38 UTC, denis-konakov commented on src/api/bookApi.ts
> +  const authorId = (await supabase.auth.getUser(await authorToken)).data.user
это лучше разнести на разные строки

2023-09-04 14:38 UTC, denis-konakov commented on src/api/userApi.ts
> +  // await supabase.auth.setSession(data.session!);
комменты нужно либо удалять, либо помечать `TODO`

2023-09-04 14:38 UTC, denis-konakov commented on src/components/TabBar/TabBar.tsx
> +import {icons} from 'src/constants/icons';
иконки в константы выносить не нужно, это актуально только для картинок. Иконки нужно импортировать напрямую. Файл иконок удали

2023-09-04 14:38 UTC, denis-konakov commented on src/components/TabBar/TabBar.tsx
> +        const svg_props = {
логику выборки иконки вынеси в отдельную функцию

2023-09-04 14:38 UTC, denis-konakov commented on src/components/TabBar/TabBar.tsx
> +            {svg_icon}
иконки и компоненты всегда именуй с большой буквы, плюс предпочитай камель кейс (camelCase)

2023-09-04 14:38 UTC, denis-konakov commented on src/navigation/AppStack.tsx
> +          const books = await getBooksRequest({page: 1});
у тебя уже есть запрос на получение списка книг при заходе в приложение. Сделай так, чтобы логика навигации отрабатывала после выполнения того запроса, а отсюда его удали

2023-09-04 14:38 UTC, denis-konakov commented on src/navigation/AppStack.tsx
> +          name="Modal"
модалка не может быть скрином, нужно сделать именно через компонент `Modal` из `react-native`

2023-09-04 14:38 UTC, denis-konakov commented on src/navigation/Navigation.tsx
> +    getToken();
пока токен не прогрузился, нужно держать сплэш скрин активным

2023-09-04 14:38 UTC, denis-konakov commented on src/screens/Catalog/Catalog.tsx
> +          {bookList.length > 0 &&
это условие не нужно, `map` просто ничего не вернет

2023-09-04 14:38 UTC, denis-konakov commented on src/screens/Profile/Profile.tsx
> +            withLabel={true}
такие пропсы можно без `={true}` прокидывать

2023-09-05 11:43 UTC, merged